version: "3"
services:
  web-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    volumes:
    - .:/usr/src/app/:rw
    - /usr/src/app/node_modules
    environment:
    - NODE_ENV=production
#    command: sh -c 'npm run build:prod && node ./server/server.js'
    command: sh -c 'node ./server.js'