//import * as ACTIONS from '../actions/Actions';

export const SET_CONFIG ='SET_CONFIG';
export const SET_HIERARCHY ='SET_HIERARCHY';
export const SET_HIERARCHY_TREE ='SET_HIERARCHY_TREE';
export const SET_CURRENTUSER ='SET_CURRENTUSER';
export const SET_ALLEGOLRS ='SET_ALLEGOLRS';
export const SET_AUDIENCEMEMBERS ='SET_AUDIENCEMEMBERS';